pcl_to_scan:
  ros__parameters:
    # Target frame for the laser scan
    target_frame: "XT_32_10hz"
    
    # Output frame (same as target frame in this case)
    output_frame: "XT_32_10hz"
    
    # Transform tolerance in seconds
    transform_tolerance: 0.05
    
    # Height filtering (Z-axis limits)
    min_height: -0.10
    max_height: 0.30
    
    # Angular range settings
    angle_min: -3.14159    # -180 degrees
    angle_max: 3.14159     #  180 degrees
    angle_increment: 0.004363323  # ~0.25 degrees
    
    # Range filtering
    range_min: 0.1
    range_max: 20.0
    
    # Scan timing
    scan_time: 0.0
    
    # Infinity handling
    use_inf: false
    inf_epsilon: 1.0
    
    # Concurrency settings
    concurrency_level: 1
    
    # Use simulation time
    use_sim_time: true

    qos_overrides:
      /scan:
        publisher:
          reliability: reliable
          durability: volatile

semantic_frontier_exploration:
  semantic_frontier_exploration_node:
    ros__parameters:
      publish_frequency: 10.0  # Hz
      min_cluster_size: 5
      max_cluster_size: 150
      value_map_namespace: "/semantic_frontier_exploration"  # Namespace for the Value Map Node
